"""
AI Model Module for MT5 Trading System

This module handles machine learning model training, prediction,
and signal generation for trading decisions.

Supported Models:
- XGBoost (Gradient Boosting)
- LightGBM (Light Gradient Boosting)
- LSTM (Long Short-Term Memory)
- Ensemble models

Author: AI Trading System
Version: 1.0.0
"""

import logging
import os
import pickle
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


class ModelType(Enum):
    """Supported ML model types."""
    XGBOOST = "xgboost"
    LIGHTGBM = "lightgbm"
    LSTM = "lstm"
    ENSEMBLE = "ensemble"


class SignalDirection(Enum):
    """Trading signal directions."""
    BUY = 1
    SELL = -1
    HOLD = 0


@dataclass
class TradingSignal:
    """
    Trading signal generated by AI model.

    Attributes:
        direction: BUY, SELL, or HOLD
        probability: Probability of direction (0.0 - 1.0)
        confidence: Model confidence score (0.0 - 1.0)
        model_name: Name of model that generated signal
        predicted_return: Expected return percentage
        features: Dictionary of input features
        timestamp: Signal generation time
    """
    direction: SignalDirection
    probability: float
    confidence: float
    model_name: str
    predicted_return: float
    features: dict
    timestamp: datetime

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            'direction': self.direction.name,
            'probability': self.probability,
            'confidence': self.confidence,
            'model_name': self.model_name,
            'predicted_return': self.predicted_return,
            'timestamp': self.timestamp.isoformat()
        }


class BaseModel(ABC):
    """Abstract base class for ML models."""

    @abstractmethod
    def train(
        self,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: Optional[np.ndarray] = None,
        y_val: Optional[np.ndarray] = None
    ) -> dict:
        """Train the model."""
        pass

    @abstractmethod
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Make predictions."""
        pass

    @abstractmethod
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict class probabilities."""
        pass

    @abstractmethod
    def save(self, path: str) -> None:
        """Save model to disk."""
        pass

    @abstractmethod
    def load(self, path: str) -> None:
        """Load model from disk."""
        pass


class XGBoostModel(BaseModel):
    """
    XGBoost model wrapper for trading signal prediction.

    XGBoost is excellent for tabular data with good interpretability
    and fast training times.
    """

    def __init__(
        self,
        n_estimators: int = 100,
        max_depth: int = 6,
        learning_rate: float = 0.1,
        min_child_weight: int = 1,
        subsample: float = 0.8,
        colsample_bytree: float = 0.8,
        random_state: int = 42
    ):
        self.model_type = ModelType.XGBOOST
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.learning_rate = learning_rate
        self.min_child_weight = min_child_weight
        self.subsample = subsample
        self.colsample_bytree = colsample_bytree
        self.random_state = random_state
        self._model = None

    def _create_model(self):
        """Create XGBoost model instance."""
        try:
            from xgboost import XGBClassifier
            return XGBClassifier(
                n_estimators=self.n_estimators,
                max_depth=self.max_depth,
                learning_rate=self.learning_rate,
                min_child_weight=self.min_child_weight,
                subsample=self.subsample,
                colsample_bytree=self.colsample_bytree,
                random_state=self.random_state,
                use_label_encoder=False,
                eval_metric='logloss'
            )
        except ImportError:
            logger.error("XGBoost not installed. Install with: pip install xgboost")
            return None

    def train(
        self,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: Optional[np.ndarray] = None,
        y_val: Optional[np.ndarray] = None
    ) -> dict:
        """Train the XGBoost model."""
        self._model = self._create_model()
        if self._model is None:
            return {'success': False, 'error': 'XGBoost not available'}

        try:
            eval_set = [(X_val, y_val)] if X_val is not None else None

            self._model.fit(
                X_train, y_train,
                eval_set=eval_set,
                verbose=False
            )

            # Get feature importance
            importance = self._model.feature_importances_

            return {
                'success': True,
                'feature_importance': importance,
                'n_features': X_train.shape[1]
            }

        except Exception as e:
            logger.error(f"Training failed: {e}")
            return {'success': False, 'error': str(e)}

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict class labels."""
        if self._model is None:
            raise ValueError("Model not trained")
        return self._model.predict(X)

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict class probabilities."""
        if self._model is None:
            raise ValueError("Model not trained")
        return self._model.predict_proba(X)

    def save(self, path: str) -> None:
        """Save model to file."""
        if self._model is None:
            raise ValueError("No model to save")
        with open(path, 'wb') as f:
            pickle.dump(self._model, f)
        logger.info(f"Model saved to {path}")

    def load(self, path: str) -> None:
        """Load model from file."""
        with open(path, 'rb') as f:
            self._model = pickle.load(f)
        logger.info(f"Model loaded from {path}")


class LightGBMModel(BaseModel):
    """
    LightGBM model wrapper for trading signal prediction.

    LightGBM is efficient for large datasets and handles
    categorical features well.
    """

    def __init__(
        self,
        n_estimators: int = 100,
        max_depth: int = 6,
        learning_rate: float = 0.1,
        num_leaves: int = 31,
        min_child_samples: int = 20,
        subsample: float = 0.8,
        colsample_bytree: float = 0.8,
        random_state: int = 42
    ):
        self.model_type = ModelType.LIGHTGBM
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.learning_rate = learning_rate
        self.num_leaves = num_leaves
        self.min_child_samples = min_child_samples
        self.subsample = subsample
        self.colsample_bytree = colsample_bytree
        self.random_state = random_state
        self._model = None

    def _create_model(self):
        """Create LightGBM model instance."""
        try:
            from lightgbm import LGBMClassifier
            return LGBMClassifier(
                n_estimators=self.n_estimators,
                max_depth=self.max_depth,
                learning_rate=self.learning_rate,
                num_leaves=self.num_leaves,
                min_child_samples=self.min_child_samples,
                subsample=self.subsample,
                colsample_bytree=self.colsample_bytree,
                random_state=self.random_state,
                verbose=-1
            )
        except ImportError:
            logger.error("LightGBM not installed. Install with: pip install lightgbm")
            return None

    def train(
        self,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: Optional[np.ndarray] = None,
        y_val: Optional[np.ndarray] = None
    ) -> dict:
        """Train the LightGBM model."""
        self._model = self._create_model()
        if self._model is None:
            return {'success': False, 'error': 'LightGBM not available'}

        try:
            eval_set = [(X_val, y_val)] if X_val is not None else None

            self._model.fit(
                X_train, y_train,
                eval_set=eval_set,
                callbacks=[lambda env: None]  # Suppress output
            )

            importance = self._model.feature_importances_
            return {
                'success': True,
                'feature_importance': importance,
                'n_features': X_train.shape[1]
            }

        except Exception as e:
            logger.error(f"Training failed: {e}")
            return {'success': False, 'error': str(e)}

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict class labels."""
        if self._model is None:
            raise ValueError("Model not trained")
        return self._model.predict(X)

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict class probabilities."""
        if self._model is None:
            raise ValueError("Model not trained")
        return self._model.predict_proba(X)

    def save(self, path: str) -> None:
        """Save model to file."""
        if self._model is None:
            raise ValueError("No model to save")
        with open(path, 'wb') as f:
            pickle.dump(self._model, f)
        logger.info(f"Model saved to {path}")

    def load(self, path: str) -> None:
        """Load model from file."""
        with open(path, 'rb') as f:
            self._model = pickle.load(f)
        logger.info(f"Model loaded from {path}")


class AIModelManager:
    """
    Manages AI models for trading signal generation.

    Responsibilities:
    - Initialize and train models
    - Generate trading signals
    - Handle model retraining
    - Ensemble predictions
    """

    def __init__(
        self,
        model_type: ModelType = ModelType.XGBOOST,
        min_confidence: float = 0.65,
        models_dir: str = "./models"
    ):
        self.model_type = model_type
        self.min_confidence = min_confidence
        self.models_dir = Path(models_dir)
        self.models_dir.mkdir(parents=True, exist_ok=True)

        self._model: Optional[BaseModel] = None
        self._feature_names: list[str] = []
        self._is_trained = False
        self._training_history: list[dict] = []

    def create_model(self) -> BaseModel:
        """Create a new model instance."""
        if self.model_type == ModelType.XGBOOST:
            return XGBoostModel()
        elif self.model_type == ModelType.LIGHTGBM:
            return LightGBMModel()
        else:
            raise ValueError(f"Unsupported model type: {self.model_type}")

    def train(
        self,
        features: pd.DataFrame,
        labels: pd.Series,
        test_size: float = 0.2,
        retrain: bool = False
    ) -> dict:
        """
        Train the model on provided data.

        Args:
            features: Feature DataFrame
            labels: Target labels
            test_size: Fraction for validation set
            retrain: Whether to retrain existing model

        Returns:
            Training results dictionary
        """
        from sklearn.model_selection import train_test_split

        # Store feature names
        self._feature_names = list(features.columns)

        # Split data
        X = features.values
        y = labels.values

        X_train, X_val, y_train, y_val = train_test_split(
            X, y, test_size=test_size, shuffle=False  # Time series - no shuffle
        )

        logger.info(f"Training on {len(X_train)} samples, validating on {len(X_val)}")

        # Create and train model
        self._model = self.create_model()
        result = self._model.train(X_train, y_train, X_val, y_val)

        if result.get('success'):
            self._is_trained = True

            # Save model
            model_path = self.models_dir / f"model_{self.model_type.value}.pkl"
            self._model.save(str(model_path))

            # Log training metrics
            train_metrics = self._calculate_metrics(X_train, y_train)
            val_metrics = self._calculate_metrics(X_val, y_val)

            self._training_history.append({
                'timestamp': datetime.now(),
                'train_accuracy': train_metrics['accuracy'],
                'val_accuracy': val_metrics['accuracy'],
                'train_f1': train_metrics['f1'],
                'val_f1': val_metrics['f1']
            })

            result.update({
                'train_metrics': train_metrics,
                'val_metrics': val_metrics
            })

        return result

    def predict(self, features: pd.DataFrame) -> Optional[TradingSignal]:
        """
        Generate trading signal from features.

        Args:
            features: Feature DataFrame

        Returns:
            TradingSignal or None if no signal
        """
        if not self._is_trained or self._model is None:
            logger.warning("Model not trained, cannot predict")
            return None

        try:
            X = features.values
            proba = self._model.predict_proba(X)[0]
            prediction = self._model.predict(X)[0]

            # Determine direction
            if len(proba) == 2:
                # Binary classification
                buy_prob = proba[1]
                prob = buy_prob
                direction = SignalDirection.BUY if prediction == 1 else SignalDirection.SELL
            else:
                # Multi-class
                buy_prob = proba[2] if len(proba) > 2 else 0
                sell_prob = proba[0] if len(proba) > 0 else 0
                prob = max(buy_prob, sell_prob)
                direction = SignalDirection.BUY if buy_prob > sell_prob else SignalDirection.SELL
                if buy_prob < 0.4 and sell_prob < 0.4:
                    direction = SignalDirection.HOLD

            # Calculate confidence based on probability margin
            confidence = abs(prob - 0.5) * 2  # Scale to 0-1

            # Check minimum confidence
            if confidence < self.min_confidence:
                direction = SignalDirection.HOLD
                confidence = 0

            # Get predicted return (simplified)
            predicted_return = (prob - 0.5) * 2 if direction != SignalDirection.HOLD else 0

            return TradingSignal(
                direction=direction,
                probability=prob,
                confidence=confidence,
                model_name=f"{self.model_type.value}_model",
                predicted_return=predicted_return,
                features=dict(features.iloc[0]) if len(features) > 0 else {},
                timestamp=datetime.now()
            )

        except Exception as e:
            logger.error(f"Prediction error: {e}")
            return None

    def predict_batch(self, features: pd.DataFrame) -> list[TradingSignal]:
        """Predict signals for multiple samples."""
        signals = []
        for i in range(len(features)):
            signal = self.predict(features.iloc[i:i+1])
            if signal:
                signals.append(signal)
        return signals

    def _calculate_metrics(self, X: np.ndarray, y: np.ndarray) -> dict:
        """Calculate model performance metrics."""
        from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

        y_pred = self._model.predict(X)

        return {
            'accuracy': accuracy_score(y, y_pred),
            'f1': f1_score(y, y_pred, average='weighted'),
            'precision': precision_score(y, y_pred, average='weighted', zero_division=0),
            'recall': recall_score(y, y_pred, average='weighted')
        }

    def load_model(self, path: str) -> bool:
        """Load model from file."""
        try:
            self._model = self.create_model()
            self._model.load(path)
            self._is_trained = True
            logger.info(f"Model loaded from {path}")
            return True
        except Exception as e:
            logger.error(f"Failed to load model: {e}")
            return False

    def get_feature_importance(self) -> Optional[pd.DataFrame]:
        """Get feature importance from trained model."""
        if not self._is_trained:
            return None

        try:
            importance = self._model._model.feature_importances_
            return pd.DataFrame({
                'feature': self._feature_names,
                'importance': importance
            }).sort_values('importance', ascending=False)
        except Exception as e:
            logger.error(f"Failed to get feature importance: {e}")
            return None

    @property
    def is_trained(self) -> bool:
        """Check if model is trained."""
        return self._is_trained


# Factory function
def create_model_manager(
    model_type: ModelType = ModelType.XGBOOST,
    min_confidence: float = 0.65,
    models_dir: str = "./models"
) -> AIModelManager:
    """Create and return an AIModelManager instance."""
    return AIModelManager(
        model_type=model_type,
        min_confidence=min_confidence,
        models_dir=models_dir
    )


# Example usage
if __name__ == "__main__":
    import tempfile

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    print("=" * 60)
    print("AI Model Module Test")
    print("=" * 60)

    # Create sample data
    np.random.seed(42)
    n_samples = 1000
    n_features = 20

    X = np.random.randn(n_samples, n_features)
    y = np.random.randint(0, 2, n_samples)  # Binary classification

    features_df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(n_features)])
    labels = pd.Series(y)

    print(f"Training data: {n_samples} samples, {n_features} features")

    # Create model manager
    manager = AIModelManager(
        model_type=ModelType.XGBOOST,
        min_confidence=0.65,
        models_dir="./temp_models"
    )

    # Train model
    print("\nTraining XGBoost model...")
    result = manager.train(features_df, labels)

    if result.get('success'):
        print(f"✓ Training successful")
        print(f"  Train accuracy: {result['train_metrics']['accuracy']:.3f}")
        print(f"  Val accuracy: {result['val_metrics']['accuracy']:.3f}")
        print(f"  Val F1: {result['val_metrics']['f1']:.3f}")

        # Test prediction
        print("\nTesting prediction...")
        test_features = features_df.iloc[:5]
        signal = manager.predict(test_features)

        if signal:
            print(f"✓ Signal generated:")
            print(f"  Direction: {signal.direction.name}")
            print(f"  Probability: {signal.probability:.3f}")
            print(f"  Confidence: {signal.confidence:.3f}")

        # Feature importance
        importance = manager.get_feature_importance()
        if importance is not None:
            print(f"\n✓ Top 5 features:")
            print(importance.head().to_string(index=False))
    else:
        print(f"✗ Training failed: {result.get('error')}")

    # Cleanup
    import shutil
    if os.path.exists("./temp_models"):
        shutil.rmtree("./temp_models")

    print("\n" + "=" * 60)
    print("AI Model Module - Complete")
    print("=" * 60)
